server:
  port: 9999
spring:
  application:
    name: pn-mall-gateway-app

  cloud:
    nacos:
      discovery: # 服务注册中心
        server-addr: 192.168.100.31:8848
      config: # 服务配置中心
        server-addr: 192.168.100.31:8848
    gateway:
      routes:
        - id: pn-mall-pms          # 商品微服务
          uri: lb://pn-mall-pms    # 微服务的名称 实现负载均衡
          predicates:
            - Path=/pms/app/**
        - id: pn-mall-cms          # 内容微服务
          uri: lb://pn-mall-cms    # 微服务的名称 实现负载均衡
          predicates:
            - Path=/cms/app/**




      # 跨域配置
      globalcors:
        # 解决 options 请求被拦截问题
        add-to-simple-url-handler-mapping: true

        corsConfigurations:
          '[/**]':
            # 允许哪些域名和端口的跨域请求
            allowedOrigins: "*"
            # 允许的跨域ajax的请求方式
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            # 允许在请求中携带的头信息
            allowedHeaders: "*"
