server:
  port: 8001

spring:
  application:
    name: pn-mall-pms # 微服务的名称
  datasource:
    url: jdbc:mysql://192.168.100.21:3306/pn_mall?useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery: # 服务注册和发现
        server-addr: 192.168.100.31:8848 # nacos server 地址
      config:
        server-addr: 192.168.100.31:8848 #配置中心

  jackson:
    # json 序列化排除值为 null 的属性
    default-property-inclusion: non_null
    # 格式化日期
    date-format: yyyy-MM-dd HH:mm:ss
    # 配置时区
    time-zone: GMT+8

# 日志配置
logging:
  pattern:
    console: '%d{HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'
  level:
    # 指定整个项目的日志级别为warn
    root: info
    # 对某个包指定单独的日志级别
    com.bjpowernode.mapper: debug