server:
  port: 8002
spring:
  application:
    name: pn-mall-cms
  datasource:
    url: jdbc:mysql://192.168.100.21:3306/pn_mall?useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery: #服务注册中心
        server-addr: 192.168.100.31:8848
      config: #服务配置中心
        server-addr: 192.168.100.31:8848
  jackson:
    # json 序列化排除值为 null 的属性
    default-property-inclusion: non_null
    # 格式化日期
    date-format: yyyy-MM-dd HH:mm:ss
    # 配置时区
    time-zone: GMT+8

  redis:
    host: 192.168.100.41
    port: 6379
    password: 123456
    lettuce:
      pool:
        enabled: true
        max-active: 8 # 最大连接数
        max-idle: 8 # 最多空闲连接
        min-idle: 0 # 最小空闲连接
        max-wait: 100 # 连接等待时间 默认值 -1
# 日志配置
logging:
  pattern:
    console: '%d{HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'
  level:
    # 指定整个项目的日志级别为info
    root: info
    # 对某个包指定单独的日志级别
    com.bjpowernode.mapper: debug

minio:
  endpoint: http://192.168.100.41:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: mall